version: '3.3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iatesting
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"

volumes:
  db_data:
