"""empty message

Revision ID: 9152d538db51
Revises: 85fae3672b3b
Create Date: 2024-09-06 00:38:05.650369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9152d538db51'
down_revision = '85fae3672b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_suite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=150), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suite_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('test_case_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'test_suite', ['suite_id'], ['id'])
        batch_op.drop_column('image_text')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image_text', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('test_case_ibfk_1', 'project', ['project_id'], ['id'])
        batch_op.drop_column('suite_id')

    op.drop_table('test_suite')
    # ### end Alembic commands ###
